pipeline:
  build: 
    image: python:3.10
    commands:
      - pip install pdm==2.6.1
      - pdm install
     # - while not ping pdgb:5432 sleep 3
      - pdm run pytest -v --cov=coffee --cov-report=term --cov-report=html testing
    environment: 
      COFFEE_APP_HOSTNAME: pgdb 
      COFFEE_APP_USERNAME: postgres
      COFFEE_APP_PASSWD: asdf

services: 
  pgdb:
    image: postgres:15.3
    environment: 
      POSTGRES_PASSWORD: asdf
      POSTGRES_USER: postgres
      COFFEE_APP_HOSTNAME: pgdb
      COFFEE_APP_USERNAME: postgres
      COFFEE_APP_PASSWD: asdf
