pipeline:
  build: 
    image: python:3.10
    commands:
      - pwd 
      - ls -la 
      - id 
      - env
      - pip install pdm==2.6.1
      - pdm install
      - pdm run pytest -v --cov=coffee --cov-report=term --cov-report=html testing
    environment: 
      COFFEE_APP_HOSTNAME: pgdb 
      COFFEE_APP_USERNAME: postgres
      COFFEE_APP_PASSWD: asdf

services: 
  pgdb:
    image: postgres:15.3
    environment: 
      POSTGRES_PASSWORD: asdf
      POSTGRES_USER: postgres
      COFFEE_APP_HOSTNAME: pgdb
      COFFEE_APP_USERNAME: postgres
      COFFEE_APP_PASSWD: asdf
