services: 
  web: 
    build: .
    ports: 
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 15s
  
  admin: 
    image: dpage/pgadmin4:7.3
    ports:  
      - "8001:80"
    environment:  
      PGADMIN_DEFAULT_EMAIL: dm@example.com 
      PGADMIN_DEFAULT_PASSWORD: asdf

  db: 
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_PASSWORD: asdf
    ports: 
      - "5432:5432"

