[tool.pdm]

[tool.pdm.scripts]
start = "uvicorn main:app --reload"

[project]
name = "coffee_app"
version = "0.0.1"
description = ""
authors = [
    {name = "Daniel Martin", email = "daniel.martin@scandio.de"},
]
dependencies = [
    "fastapi[all]>=0.95.1",
    "jinja2>=3.1.2",
]
requires-python = ">=3.10"
license = {text = "MIT"}
