[tool.pdm]

[tool.pdm.scripts]
start = "uvicorn src.main:app --reload"

[project]
name = "coffee_app"
version = "0.0.1"
description = ""
authors = [
    {name = "Daniel Martin", email = "daniel.martin@scandio.de"},
]
dependencies = [
    "fastapi>=0.95.1",
    "uvicorn>=0.22.0",
    "pydantic>=1.10.7",
]
requires-python = ">=3.10"
license = {text = "MIT"}
